/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-03-20 04:25:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/E:/SPRING%20COURSE/Spring%20test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511752906000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1616084389987L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar", Long.valueOf(1612546868701L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1611216242178L));
    _jspx_dependants.put("jar:file:/E:/SPRING%20COURSE/Spring%20test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/E:/SPRING%20COURSE/Spring%20test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1611216240564L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1597850220145L));
    _jspx_dependants.put("jar:file:/E:/SPRING%20COURSE/Spring%20test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1437576592000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" http-equiv=\"Content-Type\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no, text/html\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Home page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t <!-- Start Slider -->\r\n");
      out.write("    <div id=\"slides-shop\" class=\"cover-slides\">\r\n");
      out.write("        <ul class=\"slides-container\">\r\n");
      out.write("            <li class=\"text-left\">\r\n");
      out.write("                <img src=\"images/banner-01.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <h1 class=\"m-b-20\"><strong>Welcome To <br> TTClothes Shop</strong></h1>\r\n");
      out.write("                            <p class=\"m-b-40\">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>\r\n");
      out.write("                            <p><a class=\"btn hvr-hover\" href=\"#\">Shop New</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"text-center\">\r\n");
      out.write("                <img src=\"images/banner-02.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <h1 class=\"m-b-20\"><strong>Welcome To <br> TTClothes Shop</strong></h1>\r\n");
      out.write("                            <p class=\"m-b-40\">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>\r\n");
      out.write("                            <p><a class=\"btn hvr-hover\" href=\"#\">Shop New</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"text-right\">\r\n");
      out.write("                <img src=\"images/banner-03.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <h1 class=\"m-b-20\"><strong>Welcome To <br> TTClothes Shop</strong></h1>\r\n");
      out.write("                            <p class=\"m-b-40\">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>\r\n");
      out.write("                            <p><a class=\"btn hvr-hover\" href=\"#\">Shop New</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"slides-navigation\">\r\n");
      out.write("            <a href=\"#\" class=\"next\"><i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"prev\"><i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Slider -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Categories  -->\r\n");
      out.write("    <div class=\"categories-shop\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\r\n");
      out.write("                    <div class=\"shop-cat-box\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"images/t-shirts-img.jpg\" alt=\"\" />\r\n");
      out.write("                        <a class=\"btn hvr-hover\" href=\"#\">T-shirts</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"shop-cat-box\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"images/shirt-img.jpg\" alt=\"\" />\r\n");
      out.write("                        <a class=\"btn hvr-hover\" href=\"#\">Shirt</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\r\n");
      out.write("                    <div class=\"shop-cat-box\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"images/wallet-img.jpg\" alt=\"\" />\r\n");
      out.write("                        <a class=\"btn hvr-hover\" href=\"#\">Wallet</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"shop-cat-box\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"images/women-bag-img.jpg\" alt=\"\" />\r\n");
      out.write("                        <a class=\"btn hvr-hover\" href=\"#\">Bags</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\r\n");
      out.write("                    <div class=\"shop-cat-box\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"images/shoes-img.jpg\" alt=\"\" />\r\n");
      out.write("                        <a class=\"btn hvr-hover\" href=\"#\">Shoes</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"shop-cat-box\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"images/women-shoes-img.jpg\" alt=\"\" />\r\n");
      out.write("                        <a class=\"btn hvr-hover\" href=\"#\">Women Shoes</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Categories -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Products  -->\r\n");
      out.write("    <div class=\"products-box\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"title-all text-center\">\r\n");
      out.write("                        <h1>Featured Products</h1>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet lacus enim.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"special-menu text-center\">\r\n");
      out.write("                        <div class=\"button-group filter-button-group\">\r\n");
      out.write("                            <button class=\"active\" data-filter=\"*\">All</button>\r\n");
      out.write("                            <button data-filter=\".top-featured\">Top featured</button>\r\n");
      out.write("                            <button data-filter=\".best-seller\">Best seller</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row special-list\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 special-grid best-seller\">\r\n");
      out.write("                    <div class=\"products-single fix\">\r\n");
      out.write("                        <div class=\"box-img-hover\">\r\n");
      out.write("                            <div class=\"type-lb\">\r\n");
      out.write("                                <p class=\"sale\">Sale</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"images/img-pro-01.jpg\" class=\"img-fluid\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"mask-icon\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"why-text\">\r\n");
      out.write("                            <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                            <h5> $7.79</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 special-grid top-featured\">\r\n");
      out.write("                    <div class=\"products-single fix\">\r\n");
      out.write("                        <div class=\"box-img-hover\">\r\n");
      out.write("                            <div class=\"type-lb\">\r\n");
      out.write("                                <p class=\"new\">New</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"images/img-pro-02.jpg\" class=\"img-fluid\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"mask-icon\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"why-text\">\r\n");
      out.write("                            <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                            <h5> $9.79</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 special-grid top-featured\">\r\n");
      out.write("                    <div class=\"products-single fix\">\r\n");
      out.write("                        <div class=\"box-img-hover\">\r\n");
      out.write("                            <div class=\"type-lb\">\r\n");
      out.write("                                <p class=\"sale\">Sale</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"images/img-pro-03.jpg\" class=\"img-fluid\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"mask-icon\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"why-text\">\r\n");
      out.write("                            <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                            <h5> $10.79</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 special-grid best-seller\">\r\n");
      out.write("                    <div class=\"products-single fix\">\r\n");
      out.write("                        <div class=\"box-img-hover\">\r\n");
      out.write("                            <div class=\"type-lb\">\r\n");
      out.write("                                <p class=\"sale\">Sale</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"images/img-pro-04.jpg\" class=\"img-fluid\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"mask-icon\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"why-text\">\r\n");
      out.write("                            <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                            <h5> $15.79</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Products  -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Blog  -->\r\n");
      out.write("    <div class=\"latest-blog\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"title-all text-center\">\r\n");
      out.write("                        <h1>latest blog</h1>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet lacus enim.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                    <div class=\"blog-box\">\r\n");
      out.write("                        <div class=\"blog-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"images/blog-img.jpg\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-content\">\r\n");
      out.write("                            <div class=\"title-blog\">\r\n");
      out.write("                                <h3>Fusce in augue non nisi fringilla</h3>\r\n");
      out.write("                                <p>Nulla ut urna egestas, porta libero id, suscipit orci. Quisque in lectus sit amet urna dignissim feugiat. Mauris molestie egestas pharetra. Ut finibus cursus nunc sed mollis. Praesent laoreet lacinia elit id lobortis.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"option-blog\">\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Likes\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Views\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Comments\"><i class=\"far fa-comments\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                    <div class=\"blog-box\">\r\n");
      out.write("                        <div class=\"blog-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"images/blog-img-01.jpg\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-content\">\r\n");
      out.write("                            <div class=\"title-blog\">\r\n");
      out.write("                                <h3>Fusce in augue non nisi fringilla</h3>\r\n");
      out.write("                                <p>Nulla ut urna egestas, porta libero id, suscipit orci. Quisque in lectus sit amet urna dignissim feugiat. Mauris molestie egestas pharetra. Ut finibus cursus nunc sed mollis. Praesent laoreet lacinia elit id lobortis.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"option-blog\">\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Likes\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Views\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Comments\"><i class=\"far fa-comments\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                    <div class=\"blog-box\">\r\n");
      out.write("                        <div class=\"blog-img\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"images/blog-img-02.jpg\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-content\">\r\n");
      out.write("                            <div class=\"title-blog\">\r\n");
      out.write("                                <h3>Fusce in augue non nisi fringilla</h3>\r\n");
      out.write("                                <p>Nulla ut urna egestas, porta libero id, suscipit orci. Quisque in lectus sit amet urna dignissim feugiat. Mauris molestie egestas pharetra. Ut finibus cursus nunc sed mollis. Praesent laoreet lacinia elit id lobortis.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"option-blog\">\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Likes\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Views\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Comments\"><i class=\"far fa-comments\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Blog  -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
